services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ..:/workspace:cached 
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/anti_gaspillage?sslmode=disable
  
  flutter:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flutter
    volumes:
      - ./frontend:/workspace:cached
    ports:
      - "8000:8000"  
    environment:
      FLUTTER_WEB: true
    entrypoint: ["/bin/sh", "-c"]
    command: ["while true; do sleep 3600; done"]

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anti_gaspillage
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
